### ISSUE TITLE
Server Not Starting With 1.16.5 Version

### ISSUE THREAD

**Issue by ZombieNW** [GStefanowich/MC-Server-Protection#25]
I put the mod in my server folder and it will not start, here are the logs, I dont really have further information
Maybe this is a mod conflict but ill investigate it myself

Log Output:
`[14:10:25] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'sewing-machine'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-launch.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: de/bluecolored/bluemap/api/BlueMapAPI
        at net.TheElm.project.utilities.MapUtils.<clinit>(MapUtils.java:48) ~[sewing-machine-1.3.0_mc-1.16.5.jar:?]
        at net.TheElm.project.ServerCore.onInitializeServer(ServerCore.java:113) ~[sewing-machine-1.3.0_mc-1.16.5.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-launch.jar:?]
        ... 17 more
Caused by: java.lang.NoClassDefFoundError: de/bluecolored/bluemap/api/BlueMapAPI
        at net.TheElm.project.utilities.MapUtils.<clinit>(MapUtils.java:48) ~[sewing-machine-1.3.0_mc-1.16.5.jar:?]
        at net.TheElm.project.ServerCore.onInitializeServer(ServerCore.java:113) ~[sewing-machine-1.3.0_mc-1.16.5.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-launch.jar:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: de.bluecolored.bluemap.api.BlueMapAPI
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_282]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_282]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
        at net.TheElm.project.utilities.MapUtils.<clinit>(MapUtils.java:48) ~[sewing-machine-1.3.0_mc-1.16.5.jar:?]
        at net.TheElm.project.ServerCore.onInitializeServer(ServerCore.java:113) ~[sewing-machine-1.3.0_mc-1.16.5.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-launch.jar:?]
        ... 17 more`

**Comment by GStefanowich** [comment]
Thanks for sharing the crash report. If there are any other issues with the release definitely let me know.

This crash seems to be from beginning to add integration with other mods, in this case BlueMap. I was also working on adding support for a permissions mod.

It seems the BlueMap API (Which is used to integrate) wasn't packaged into my release when I did build it, I'll create a new build in a little while

**Comment by GStefanowich** [comment]
A new [1.3.1 for 1.16.5](https://github.com/GStefanowich/MC-Server-Protection/releases/tag/v1.3.1) release is now available.

Please let me know of any other issues you may come across
