### ISSUE TITLE
Registry remapping failed! CLIENT

### ISSUE THREAD

**Issue by RippAlone** [GStefanowich/MC-Server-Protection#41]
[14:38:17] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:block_entity_type contains IDs unknown to the receiver!
 - sewing-machine:warps_lectern
 - sewing-machine:guide_lectern
 
 PLEASE HELP ME

**Comment by RippAlone** [comment]
14:38:17] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:block_entity_type contains IDs unknown to the receiver!
 - sewing-machine:warps_lectern
 - sewing-machine:guide_lectern
	at net.minecraft.class_2370.remap(class_2370.java:694) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:283) ~[fabric-registry-sync-v0-0.8.6+533be9ba65-b779c3ab09171f9.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:89) ~[fabric-registry-sync-v0-0.8.6+533be9ba65-b779c3ab09171f9.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]

**Comment by RippAlone** [comment]
[13:39:32] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[13:39:32] [main/INFO]: Loading 95 mods:
	- advancednetherite 1.2.0-1.18
	- awesomedungeon 1.1.4
	- betterfpsdist 1.18-1.3
	- bettersleeping 0.5.1+1.18
	- blue_endless_jankson 1.2.1 via jankson
	- cloth-api 2.0.54
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-client-events-v0 2.0.54 via cloth-api
	- cloth-common-events-v1 2.0.54 via cloth-api
	- cloth-config 6.1.48
	- cloth-datagen-api-v1 2.0.54 via cloth-api
	- cloth-scissors-api-v1 2.0.54 via cloth-api
	- cloth-utils-v1 2.0.54 via cloth-api
	- com_typesafe_config 1.4.1 via confabricate
	- confabricate 2.2.0-SNAPSHOT+4.1.1 via croptopia
	- croptopia 1.7.4
	- dynamicsoundfilters 1.3.0+1.18
	- dynview 1.18-1.5
	- fabric 0.45.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cd14 via bettersleeping
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957165 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca33514 via bettersleeping
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.8.6+533be9ba65 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9565 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9565 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5565 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fallingtree 2.16.1
	- fiber 0.23.0-2 via patchouli
	- inmis 2.4.0-1.18
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- iris 1.1.3
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- levelz 1.1.3
	- libgui 5.0.0-beta.2+1.18-rc1 via levelz
	- libninepatch 1.1.0 via libgui
	- minecraft 1.18.1
	- modmenu 3.0.1
	- more_gems 1.3.53
	- mostructures 1.3.0-pre1+1.18
	- omega-config 1.0.8 via inmis
	- org_anarres_jcpp 1.4.14 via iris
	- org_apache_commons_commons-text 1.9 via bettersleeping
	- org_joml_joml 1.10.2 via sodium
	- org_slf4j_slf4j-api 1.7.12 via iris
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- patchouli 1.18.1-61-FABRIC
	- pugh_tools 1.1.15 via more_gems
	- seasons 1.3-BETA+1.18
	- sodium 0.4.0-alpha5+build.9
	- stoneholm 1.4.1
	- twm 0.2
	- waystones 2.4.1
	- yigd 1.2.8B

**Comment by zemoire** [comment]
have you found the fix for this?

**Comment by GStefanowich** [comment]
This looks like an issue with the newer version of Fabric API.

Fabric API now bundles `fabric-registry-sync` that seems to make sure that anything that is registered on the server is also registered on the client. The problem though is that the client doesn't need to know the `BlockEntities` that are registered serverside in the case of this mod.

Thanks @RippAlone for providing the mods that you're using.

My personal server is using [Fabric API 0.44.0 for 1.18](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3546679), where it appears that `fabric-registry-sync` has not yet been included, and thus explains why I haven't run into this problem before.

I'll have to look into a solution when I have more free time.

**Comment by GStefanowich** [comment]
Currently looking into this issue, I've updated my Fabric API to `0.46.4 for 1.18` and can't replicate this issue. Making an unreplicable for now, let me know if updating Fabric API if you still have this issue, I'll try to investigate further

**Comment by JackGlobetrotter** [comment]
i am getting the same error, have been using fabric loader v. 0.12.12 and api 0.44.x, 
tried updating to fabric loader 0.13.3 and api to 0.46.4, but the error still persists, 

here are my installed mods:
```````
 Loading 184 mods:
	- ae2 10.0.0
	- animal_feeding_trough 1.0.3+1.18.1
	- annotateddi 2.0.4+1.18 via fireplacelib
	- anvilrestoration-fabric 1.1
	- aopalliance_aopalliance 1.0 via annotateddi
	- appleskin 2.3.0+mc1.18.1
	- architectury 3.6.17
	- audaki_cart_engine 1.0.2
	- bclib 1.3.4
	- bedrockwaters 1.6.0+1.18.1
	- betteranimalsplus 1.18.1-11.0.4
	- betterbeds 1.2.0
	- betterend 1.0.2
	- betternether 6.0.10
	- bettersafebed 1.18-fabric-a
	- bettersleeping 0.5.1+1.18
	- betterthanmending 1.3.0
	- bfapi 1.3.2
	- blue_endless_jankson 1.2.1 via jankson
	- byg 1.3.5.12
	- cardinal-components-base 4.0.0 via trinkets
	- cardinal-components-entity 4.0.0 via trinkets
	- chainsuspension 1.0.0
	- chipped 1.2
	- chunky 1.2.164
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48
	- collective-fabric 4.1
	- com_electronwill_night-config_core 3.6.5 via couplings
	- com_electronwill_night-config_toml 3.6.5 via couplings
	- com_google_inject_guice 5.0.1 via annotateddi
	- com_typesafe_config 1.4.1 via confabricate
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- compostable-rottenflesh 1.0.0
	- confabricate 2.2.0-SNAPSHOT+4.1.1 via croptopia
	- couplings 1.7.1+1.18
	- croptopia 1.8.0
	- customportalapi 0.0.1-beta47-1.18 via mining_dims
	- day_dream 1.0.4
	- discerning_furnace 1.0.5+MC1.18-1.18.1
	- dispenser_configurator 1.2.1+MC1.18-1.18.1
	- earthtojavamobs 1.7.4+1.18
	- expanded_armor_enchanting 1.0.2
	- expanded_axe_enchanting 1.0.3
	- expanded_weapon_enchanting 1.0.2
	- fabric 0.46.4+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.8+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.6+3ac43d9565 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.6+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.11+b4f4f6cd65 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.4+d7c144a865 via fabric
	- fabric-object-builders-v0 0.7.12+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via universal-graves
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.14+713c266865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.8+d7c144a865 via fabric
	- fabric-tool-attribute-api-v1 1.3.8+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.9+d7c144a865 via fabric
	- fabric-tree-chopper 0.8.2
	- fabrication 2.3.0_01
	- fabricloader 0.13.3
	- fabricsit 1.7.1
	- fabrilousupdater 2.5+1.18.1
	- farmersdelight 1.18.1-0.2.0
	- fastbench 1.18.1-3
	- fastfurnace 1.18-4
	- feature_nbt_deadlock_be_gone 1.0.1+1.18.1
	- ferritecore 4.1.1
	- fiber 0.23.0-2 via patchouli
	- fireplacelib 6.2.2+1.18
	- fishing 1.1.0
	- full_slabs 3.3.4
	- glassential 1.3.0
	- grindenchantments 1.5.0+1.18
	- haulinghog 1.0.3
	- hologram-api 0.2.1+1.18-pre5 via universal-graves
	- homecamp 2.2.1+1.18
	- horsebuff 1.1.2
	- inmis 2.4.0-1.18
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- ironchests 1.5.3
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- javax_inject_javax_inject 1 via annotateddi
	- kanos_config 0.1.4+1.14.4-1.17.1 via statement
	- krypton 0.1.6
	- lengthyladders 1.0.5
	- libgui 5.0.0-beta.2+1.18-rc1 via ironchests
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.7
	- lovely_snails 1.0.3+1.18
	- maybe-data 1.0.1-1.17 via wolveswitharmor
	- micalibria 2.0.1 via full_slabs
	- midnightlib 0.3.1 via rocks
	- minecraft 1.18.1
	- mining_dims 1.2.41
	- mo_glass 1.6.1-MC1.19_deep_dark_experimental_snapshot-1
	- more_gems 1.3.59
	- morevillagers-fabric 3.1.1-SNAPSHOT
	- mostructures 1.3.0-pre1+1.18
	- no_null_processors 2.0.1+1.18.1
	- noexpensive 1.18-Fabric-1.2.0
	- npcvariety 2.2.2
	- omega-config 1.0.8 via inmis
	- org_apache_commons_commons-text 1.9 via bettersleeping
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- packet_tweaker 0.2.0+1.18-pre1 via polymer
	- patchouli 1.18.1-64-FABRIC
	- placeholder-api 1.1.3+1.17.1 via universal-graves
	- plant-based 0.10.1
	- polymer 0.2.0-beta.15+1.18.1 via universal-graves
	- polymer-legacy 0.1.9+0.2.0-beta.15+1.18.1 via polymer
	- pride 1.1.0+1.17 via fabrication
	- pugh_lib 1.2.15 via veggie_way
	- pugh_tools 1.1.17 via more_gems
	- repurposed_structures 3.3.3+1.18.1
	- rocks 1.5.2
	- roughlyenoughitems 7.1.390
	- roughlyenoughresources 2.3.0
	- roughlysearchable 2.3.0+1.18.1
	- rutreplantswamp 0.0.2
	- server_translations_api 1.4.8+1.18-pre1 via universal-graves
	- sewing-machine 1.5.1
	- sgui 1.0.0-rc6+1.18-pre5 via universal-graves
	- sign_editor 0.8.3
	- smoothboot 1.18-1.7.0
	- snowytrees 1.0.0
	- starlight 1.0.0+fabric.d0a3220
	- statement 4.2.1+1.14.4-1.18.1 via micalibria
	- statement_vanilla_compatibility 1.0.1+1.16.5-1.17 via statement
	- static-content 1.0.1-1.16.2 via wolveswitharmor
	- staticdata 1.1.2 via static-content
	- stoneholm 1.4.2
	- suitablystackablestew 1.1.2
	- team_reborn_energy 2.0.0-beta1 via ae2
	- terrablender 1.1.0.77
	- ticktock 1.3.1
	- trampledisablerfabric 1.0.4
	- trinkets 3.1.0
	- unforgivingvoid 3.1.1+1.18
	- universal-graves 2.0.0-beta.4.1+1.18.1
	- unlimiteddragoneggs 1.3.1
	- vanillaenhanced 2.0.1
	- veggie_way 1.2.30
	- wolveswitharmor 1.7.0-1.18
	- worldedit 7.2.8+6008-1246d61
	- xaeroworldmap 1.20.3.1
	- zombify 0.1.0
````````


client versions are identical.

**Comment by JackGlobetrotter** [comment]
i tried to investigate this issue, which seems to occur when running the mod with architectury and betteranimalsplus for me. looking in it the next days:
architectury wraps the vanilla registry, which could interfere with block registry of this mod

**Comment by Zunwolf1896** [comment]
This appears to be the main thread for this issue, i'd like to add my experience in case there is anything similar that might help find the root of the problem.

Using fabric API 0.46.6+1.18 as well, having the same issue,

Using the mods in this mopack here: https://www.curseforge.com/minecraft/modpacks/wolfqueens-origins/files/all

I assume this means this mod is unable to be used until a fix is found, then? 

(Edit I accidentally put API 1.16 instead of 1.18)

**Comment by JackGlobetrotter** [comment]
> This appears to be the main thread for this issue, i'd like to add my experience in case there is anything similar that might help find the root of the problem.
> 
> Using fabric API 0.46.6+1.16 as well, having the same issue,
> 
> Using the mods in this mopack here: https://www.curseforge.com/minecraft/modpacks/wolfqueens-origins/files/all
> 
> I assume this means this mod is unable to be used until a fix is found, then?

could you provide a list of the used mods please? i do not have any modpack loader installed.

**Comment by JackGlobetrotter** [comment]
> This appears to be the main thread for this issue, i'd like to add my experience in case there is anything similar that might help find the root of the problem.
> 
> Using fabric API 0.46.6+1.16 as well, having the same issue,
> 
> Using the mods in this mopack here: https://www.curseforge.com/minecraft/modpacks/wolfqueens-origins/files/all
> 
> I assume this means this mod is unable to be used until a fix is found, then?

your modpack uses architectury api and better animals plus, mods which seem to cause the error (at least on my side). is the error message for 1.16 any different?

**Comment by GStefanowich** [comment]
> Using fabric API 0.46.6+1.16 as well, having the same issue,

Do you mean to say 0.46.6+1.18?

> your modpack uses architectury api and better animals plus, mods which seem to cause the error (at least on my side).

Installing both Architectury API and Better Animals Plus also begins causing this issue for me, so it's confirmable at least. But it appears to be an issue with Architectury then?

Not all who have had this problem use Better Animals, but all are using Architectury, so I'm assuming that any mod that relies on Architectury causes it to wrap the vanilla registry. Using Architectury by itself did not cause any problems to arise, but it probably never ran anything without having dependents.

**Comment by JackGlobetrotter** [comment]
> I'm assuming that any mod that relies on Architectury causes it to wrap the vanilla registry. Using Architectury by itself did not cause any problems to arise, but it probably never ran anything without having dependents.

Yes i think the problem is the architectury wrapper, which does only load if it is required by any mod. I am not sure that there is any easy fix for this mod.

**Comment by Zunwolf1896** [comment]
> > This appears to be the main thread for this issue, i'd like to add my experience in case there is anything similar that might help find the root of the problem.
> > Using fabric API 0.46.6+1.16 as well, having the same issue,
> > Using the mods in this mopack here: https://www.curseforge.com/minecraft/modpacks/wolfqueens-origins/files/all
> > I assume this means this mod is unable to be used until a fix is found, then?
> 
> your modpack uses architectury api and better animals plus, mods which seem to cause the error (at least on my side). is the error message for 1.16 any different?

Ahh this is a typo, it is 1.18 that I use, sorry.

**Comment by JackGlobetrotter** [comment]
I think i have found a solution, PR coming later
@GStefanowich  i have one question: should there be a lectern block displaying a custom interface ? Or am i understanding something wrong?

**Comment by GStefanowich** [comment]
> I think i have found a solution, PR coming later @GStefanowich i have one question: should there be a lectern block displaying a custom interface ? Or am i understanding something wrong?

The two block entities are lectern block replacements, yes. Though it's not a custom interface.

Technically it could be replaced by a Lectern Interface Mixin, but that's unnecessary overhead for a direct replacement.

There are two BlockEntities I've implemented. Both don't use the vanilla synced-flipping-through-the-book.

`sewing-machine:warps_lectern` Shows the player a Book that is unique to the player that shows them all of their waystones. Attempting to take the book teleports them to their waystone.

`sewing-machine:guide_lectern` Shows the player a Guide Book from the `guides.json` file. Taking the book gives the player a copy of the book, without removing it from the lectern.

**Comment by JackGlobetrotter** [comment]
i am maybe making a stupid mistake, but in the game i am not able to find these blocks at all, they should be accessible as ````/give .... sewing-machine:guide_lectern```` , no? 
I am really sorry, just trying to understand how  blockentity works...

**Comment by GStefanowich** [comment]
> i am maybe making a stupid mistake, but in the game i am not able to find these blocks at all, they should be accessible as `/give .... sewing-machine:guide_lectern` , no?

No, they are only `Block Entities`, not `Blocks` themselves.

SewingMachine works entirely as a Server-Side mod, no client modding required. Custom Blocks and Custom Interfaces require modding the Client.

A `Block Entity` only exists on the Server-Side, and holds the information about the Block. `Chests`, `Hoppers`, `Enderchests`, `Command Blocks`, `Furnaces`, and `Lecterns` are examples of blocks with `Block Entities`. Things like `Dirt` don't have `Block Entities` because they don't hold any extra information.

There are commands to modify a `Lectern Block` to change the `Block Entity`,

`/waystones lectern set` is probably the easier one because it doesn't require having anything in the `guides.json` file. Just look at a Lectern and run the command, which changes the Block entity to `sewing-machine:warps_lectern`. To get a `sewing-machine:guide_lectern` Block Entity would be `/sewing-machine guides <book_name> set`

**Comment by JackGlobetrotter** [comment]
@GStefanowich  thanks a lot for your help, got really confused between blocks and blockentities. Just trying to make sur that my fix does not brake any functionally.

**Comment by GStefanowich** [comment]
@JackGlobetrotter A fix that I've thought of, but haven't had the time to test, is to Mixin to the Vanilla BlockEntity registry myself. Currently I'm using `Fabric API` to handle the BlockEntity and Command registrations. Fabric API wraps these registrations into a "Mod Registry" rather than the Vanilla Registry.

I'm not sure if adding them myself to the Vanilla Registry would fix the problem. I'm not sure if Architectury reads the Vanilla one, or uses Fabric API itself.

**Comment by JackGlobetrotter** [comment]
> A fix that I've thought of, but haven't had the time to test, is to Mixin to the Vanilla BlockEntity registry myself. Currently I'm using `Fabric API` to handle the BlockEntity and Command registrations. Fabric API wraps these registrations into a "Mod Registry" rather than the Vanilla Registry.

Your idea is much more elegant than my "fix" (#57) but i have to admit that i do not know a whole lot about MC mod development and java mixins.

**Comment by xXFlyingBananaXx** [comment]
still isnt fixed? i have the same issue on Valhelsia: Enhanced Vanilla Modpack
would be cool if fixed :D

**Comment by GStefanowich** [comment]
> would be cool if fixed :D
- @xXFlyingBananaXx 

This issue should be fixed as of `1.5.2 for 1.18.2`, *however*, the mod needs to be installed on both the server **and** the client. There is a release of `Valhelsia: Enhanced Vanilla Modpack` for 1.18.2.  

----

Essentially,

If there are any mods on the server that trigger Fabric API's "registry-sync" (Mods that add blocks or items) then `Sewing Machine` also gets caught up in this. So adding the mod to the client fixes the problem.
