### ISSUE TITLE
Mod incompatibility with Requiem

### ISSUE THREAD

**Issue by JennyCatCake** [GStefanowich/MC-Server-Protection#58]
Running Sewing-Machine with Requiem makes the server crash. 
Server Log:

[00:08:57] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
[00:08:57] [main/INFO]: Loading 60 mods:
	- apoli 2.2.2 via origins
	- automatone 0.5.0 via requiem
	- blabber 0.1.2 via requiem
	- calio 1.4.2 via apoli
	- cardinal-components-base 4.1.2 via requiem
	- cardinal-components-entity 4.1.2 via requiem
	- cardinal-components-scoreboard 4.1.2 via requiem
	- cardinal-components-world 4.1.2 via requiem
	- chime 1.2.0-SNAPSHOT via requiem
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.0.42 via apoli
	- fabric 0.46.6+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.9+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.7+3ac43d9565 via fabric
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.7+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.12+b4f4f6cd65 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.5+737332ce65 via fabric
	- fabric-object-builders-v0 0.7.13+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via requiem
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.15+8906aafd65 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.9+d7c144a865 via fabric
	- fabric-tool-attribute-api-v1 1.3.9+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.10+c329913d65 via fabric
	- fabricloader 0.13.3
	- fiber 0.23.0-2 via requiem
	- impersonate 2.4.1 via requiem
	- java 17
	- locki 0.7.0 via requiem
	- minecraft 1.18.1
	- origins 1.3.1
	- playerabilitylib 1.5.0 via requiem
	- reach-entity-attributes 2.1.1 via origins
	- requiem 2.0.0-beta.7
	- requiem-core 2.0.0-beta.7 via requiem
	- requiemapi 2.0.0-beta.7 via requiem
	- sewing-machine 1.5.1
[00:08:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/F:/Minecraft%20Servers/Modded%20Fabric/Humans%20VS%20Ghosties/1.18.1%20Humans%20VS%20Ghosties%202.2%20-%20Creative%20Testing/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[00:08:58] [main/INFO]: Compatibility level set to JAVA_16
[00:09:07] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zff000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[00:09:13] [main/INFO]: Apoli 2.2.2 has initialized. Ready to power up your game!
[00:09:14] [main/INFO]: Origins 1.3.1 is initializing. Have fun!
[00:09:16] [main/INFO]: [SEW] Sewing Machine utilities mod is starting.
[00:09:16] [main/INFO]: [SEW] Initializing Database.
[00:09:16] [main/INFO]: [SEW] Loading configuration file (122 options).
[00:09:16] [main/INFO]: [SEW] Skipping Database Initialization (Unused)
[00:09:16] [main/INFO]: [SEW] Finished loading.
[00:09:19] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:09:22] [main/WARN]: Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack '.\world\datapacks\baby-mobs-v1-1-0.zip'
[00:09:23] [main/INFO]: [SEW] Registering our commands.
[00:09:24] [main/FATAL]: Failed to start the minecraft server
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.field_19414" is null
	at net.minecraft.class_1928$class_4314.method_20775(class_1928.java:246) ~[server-intermediary.jar:?]
	at net.fabricmc.fabric.impl.gamerule.EnumRuleType.method_20775(EnumRuleType.java:55) ~[fabric-game-rule-api-v1-1.0.11+d7c144a865-2ad1ab7eeeff5c85.jar:?]
	at net.TheElm.project.commands.WorldCommand$1.method_20762(WorldCommand.java:65) ~[sewing-machine-1.5.1_mc-1.18.1.jar:?]
	at net.minecraft.class_1928.method_20745(class_1928.java:171) ~[server-intermediary.jar:?]
	at net.minecraft.class_1928.method_20750(class_1928.java:164) ~[server-intermediary.jar:?]
	at java.util.TreeMap.forEach(TreeMap.java:1282) ~[?:?]
	at net.minecraft.class_1928.method_20744(class_1928.java:164) ~[server-intermediary.jar:?]
	at net.TheElm.project.commands.WorldCommand.register(WorldCommand.java:61) ~[sewing-machine-1.5.1_mc-1.18.1.jar:?]
	at net.TheElm.project.ServerCore.lambda$onInitializeServer$0(ServerCore.java:150) ~[sewing-machine-1.5.1_mc-1.18.1.jar:?]
	at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41) ~[fabric-command-api-v1-1.1.7+d7c144a865-6e29cd4dbfeed4d9.jar:?]
	at net.minecraft.class_2170.handler$zdh000$fabric_addCommands(class_2170.java:547) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:246) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:88) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:159) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]

**Comment by Rage-GitHub** [comment]
Can confirm, just tested SEW without Requiem on my server and it does indeed cause a conflict.
